export VOLCOMP_LIB=$HOME/m7_wholevol/lib/libvolcomp.so
export PYTHONPATH=$HOME/volume-compressor/python:$HOME/m7_wholevol/rvsm
export M7W_WORK=/vesuvius/m7_wholevol
export M7W_HOME=$HOME/m7_wholevol
export M7W_RUN_TS=20260925170000
export M7W_STRIDE=128      # new volumes; a started volume keeps its pinned params (0343P, 0009B: 96)
export M7W_CT_SMOOTH=2      # volcomp decode-only deblocking of the CT (user decision 09-25), pinned per volume
export NUMPY_MADVISE_HUGEPAGE=0
PY=$HOME/usrm2/.venv/bin/python
T=$HOME/m7_wholevol/rvsm/tools/m7_wholevol.py
